FROM clearlinux/python:3.7

RUN swupd bundle-add python-extras
RUN pip install -i https://pypi.douban.com/simple https://storage.googleapis.com/intel-optimized-tensorflow/intel_tensorflow-1.14.0-cp37-cp37m-manylinux1_x86_64.whl
